/* Generated by re2c 0.16 on Thu Sep 29 17:01:43 2016 */
#line 1 "lexer.re"
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

#include "lexer.h"

struct token lex(const char *input)
{
	int len = strlen(input);
	int marker;
	int ctxmarker;
	int index = 0;
#define YYCTYPE        char
#define YYPEEK()       input[index]
#define YYSKIP()       index++
#define YYBACKUP()     marker = index
#define YYBACKUPCTX()  ctxmarker = index
#define YYRESTORE()    index = marker
#define YYRESTORECTX() index = ctxmarker
#define YYLESSTHAN(n)  len - index < n
#define YYFILL(n)      {}
	
#line 26 "lexer.c"
{
	char yych;
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy4;
	case '(':	goto yy7;
	case ')':	goto yy9;
	case '*':	goto yy11;
	case '+':	goto yy13;
	case '-':	goto yy15;
	case '/':	goto yy17;
	case '0':	goto yy19;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy20;
	default:	goto yy2;
	}
yy2:
	YYSKIP ();
yy3:
#line 35 "lexer.re"
	{ return (struct token){ 0, 0 }; }
#line 56 "lexer.c"
yy4:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy4;
	default:	goto yy6;
	}
yy6:
#line 44 "lexer.re"
	{ return (struct token){ -1, index }; }
#line 68 "lexer.c"
yy7:
	YYSKIP ();
#line 42 "lexer.re"
	{ return (struct token){ TOK_BRO, index }; }
#line 73 "lexer.c"
yy9:
	YYSKIP ();
#line 43 "lexer.re"
	{ return (struct token){ TOK_BRC, index }; }
#line 78 "lexer.c"
yy11:
	YYSKIP ();
#line 40 "lexer.re"
	{ return (struct token){ TOK_TIMES, index }; }
#line 83 "lexer.c"
yy13:
	YYSKIP ();
#line 38 "lexer.re"
	{ return (struct token){ TOK_PLUS, index }; }
#line 88 "lexer.c"
yy15:
	YYSKIP ();
#line 39 "lexer.re"
	{ return (struct token){ TOK_MINUS, index }; }
#line 93 "lexer.c"
yy17:
	YYSKIP ();
#line 41 "lexer.re"
	{ return (struct token){ TOK_DIVIDE, index }; }
#line 98 "lexer.c"
yy19:
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'X':
	case 'x':	goto yy23;
	default:	goto yy3;
	}
yy20:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy20;
	default:	goto yy22;
	}
yy22:
#line 36 "lexer.re"
	{ return (struct token){ TOK_INTEGER, index }; }
#line 127 "lexer.c"
yy23:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy25;
	default:	goto yy24;
	}
yy24:
	YYRESTORE ();
	goto yy3;
yy25:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy25;
	default:	goto yy27;
	}
yy27:
#line 37 "lexer.re"
	{ return (struct token){ 2, index }; }
#line 190 "lexer.c"
}
#line 46 "lexer.re"

}