/* Generated by re2c 0.16 on Thu Sep 29 10:37:09 2016 */
#line 1 "lexer.re"
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

struct token
{
	int type;
	int length;
};

static struct token lex(const char *input)
{
	int len = strlen(input);
	int marker;
	int ctxmarker;
	int index = 0;
#define YYCTYPE        char
#define YYPEEK()       input[index]
#define YYSKIP()       index++
#define YYBACKUP()     marker = index
#define YYBACKUPCTX()  ctxmarker = index
#define YYRESTORE()    index = marker
#define YYRESTORECTX() index = ctxmarker
#define YYLESSTHAN(n)  len - index < n
#define YYFILL(n)      {}
	
#line 30 "lexer.c"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy4;
	case '*':
	case '+':
	case '/':	goto yy7;
	case '-':	goto yy9;
	case '0':	goto yy10;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy11;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy14;
	case 'S':	goto yy16;
	case 's':	goto yy17;
	default:	goto yy2;
	}
yy2:
	YYSKIP ();
yy3:
#line 39 "lexer.re"
	{ return (struct token){ 0, 0 }; }
#line 86 "lexer.c"
yy4:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy4;
	default:	goto yy6;
	}
yy6:
#line 43 "lexer.re"
	{ return (struct token){ 4, index }; }
#line 98 "lexer.c"
yy7:
	YYSKIP ();
yy8:
#line 42 "lexer.re"
	{ return (struct token){ 3, index }; }
#line 104 "lexer.c"
yy9:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '>':	goto yy18;
	default:	goto yy8;
	}
yy10:
	yyaccept = 0;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'X':
	case 'x':	goto yy20;
	default:	goto yy3;
	}
yy11:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy11;
	default:	goto yy13;
	}
yy13:
#line 40 "lexer.re"
	{ return (struct token){ 1, index }; }
#line 141 "lexer.c"
yy14:
	YYSKIP ();
yy15:
#line 44 "lexer.re"
	{ return (struct token){ 5, index }; }
#line 147 "lexer.c"
yy16:
	yyaccept = 1;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'T':
	case 't':	goto yy22;
	default:	goto yy15;
	}
yy17:
	yyaccept = 0;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'T':
	case 't':	goto yy22;
	default:	goto yy3;
	}
yy18:
	YYSKIP ();
#line 45 "lexer.re"
	{ return (struct token){ 6, index }; }
#line 172 "lexer.c"
yy20:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy23;
	default:	goto yy21;
	}
yy21:
	YYRESTORE ();
	if (yyaccept == 0) {
		goto yy3;
	} else {
		goto yy15;
	}
yy22:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'R':
	case 'r':	goto yy26;
	default:	goto yy21;
	}
yy23:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy23;
	default:	goto yy25;
	}
yy25:
#line 41 "lexer.re"
	{ return (struct token){ 2, index }; }
#line 247 "lexer.c"
yy26:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	default:	goto yy21;
	}
}
#line 46 "lexer.re"

}

int main(int argc, char **argv)
{
    for (int i = 1; i < argc; ++i)
		{
			char *input = argv[i];
			printf("%s\n", input);
			while(true)
			{
				struct token token = lex(input);
				printf ("  (%d, %d): '", token.type, token.length);
				fwrite(input, token.length, 1, stdout);
				printf("'\n");
				if(token.type == 0)
					break;
				input += token.length;
				if(*input == 0)
					break;
			}
    }
    return 0;
}