#define TOK_PLUS                            1
#define TOK_MINUS                           2
#define TOK_DIVIDE                          3
#define TOK_TIMES                           4
#define TOK_ASS                             5
#define TOK_VAR                             6
#define TOK_BRO                             7
#define TOK_BRC                             8
#define TOK_INTEGER                         9
#define TOK_FUN                            10
#define TOK_COMMA                          11
