#define TOK_PLUS                             1
#define TOK_MINUS                            2
#define TOK_DIVIDE                           3
#define TOK_TIMES                            4
#define TOK_AND                              5
#define TOK_OR                               6
#define TOK_XOR                              7
#define TOK_NOT                              8
#define TOK_LESS                             9
#define TOK_LESSEQ                          10
#define TOK_GREATER                         11
#define TOK_GREATEREQ                       12
#define TOK_EQ                              13
#define TOK_NEQ                             14
#define TOK_ASS                             15
#define TOK_ID                              16
#define TOK_BANG                            17
#define TOK_BRO                             18
#define TOK_BRC                             19
#define TOK_INTEGER                         20
#define TOK_BOOL                            21
#define TOK_STRING                          22
#define TOK_COMMA                           23
