#define TOK_PLUS                            1
#define TOK_MINUS                           2
#define TOK_DIVIDE                          3
#define TOK_TIMES                           4
#define TOK_AND                             5
#define TOK_OR                              6
#define TOK_XOR                             7
#define TOK_NOT                             8
#define TOK_ASS                             9
#define TOK_ORDER                          10
#define TOK_VAR                            11
#define TOK_BRO                            12
#define TOK_BRC                            13
#define TOK_INTEGER                        14
#define TOK_BOOL                           15
#define TOK_STRING                         16
#define TOK_FUN                            17
#define TOK_COMMA                          18
