/* Generated by re2c 0.16 on Fri Sep 30 12:15:39 2016 */
#line 1 "src/lexer.re"
#include "basic/lexer.h"
#include "string.h"
#include <stdbool.h>

struct token lex(const char *input)
{
	int len = str_len(input);
	int marker;
	int ctxmarker;
	int index = 0;
	
	// Mark all variables as used
	(void)len;
	(void)marker;
	(void)ctxmarker;
	(void)index;
	
#define YYCTYPE        char
#define YYPEEK()       input[index]
#define YYSKIP()       index++
#define YYBACKUP()     marker = index
#define YYBACKUPCTX()  ctxmarker = index
#define YYRESTORE()    index = marker
#define YYRESTORECTX() index = ctxmarker
#define YYLESSTHAN(n)  len - index < n
#define YYFILL(n)      {}
	
#line 31 "src/lexer.c"
{
	char yych;
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy4;
	case '(':	goto yy7;
	case ')':	goto yy9;
	case '*':	goto yy11;
	case '+':	goto yy13;
	case '-':	goto yy15;
	case '/':	goto yy17;
	case '0':	goto yy19;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy20;
	default:	goto yy2;
	}
yy2:
	YYSKIP ();
yy3:
#line 40 "src/lexer.re"
	{ return (struct token){ 0, 0 }; }
#line 61 "src/lexer.c"
yy4:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy4;
	default:	goto yy6;
	}
yy6:
#line 49 "src/lexer.re"
	{ return (struct token){ -1, index }; }
#line 73 "src/lexer.c"
yy7:
	YYSKIP ();
#line 47 "src/lexer.re"
	{ return (struct token){ TOK_BRO, index }; }
#line 78 "src/lexer.c"
yy9:
	YYSKIP ();
#line 48 "src/lexer.re"
	{ return (struct token){ TOK_BRC, index }; }
#line 83 "src/lexer.c"
yy11:
	YYSKIP ();
#line 45 "src/lexer.re"
	{ return (struct token){ TOK_TIMES, index }; }
#line 88 "src/lexer.c"
yy13:
	YYSKIP ();
#line 43 "src/lexer.re"
	{ return (struct token){ TOK_PLUS, index }; }
#line 93 "src/lexer.c"
yy15:
	YYSKIP ();
#line 44 "src/lexer.re"
	{ return (struct token){ TOK_MINUS, index }; }
#line 98 "src/lexer.c"
yy17:
	YYSKIP ();
#line 46 "src/lexer.re"
	{ return (struct token){ TOK_DIVIDE, index }; }
#line 103 "src/lexer.c"
yy19:
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'X':
	case 'x':	goto yy23;
	default:	goto yy3;
	}
yy20:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy20;
	default:	goto yy22;
	}
yy22:
#line 41 "src/lexer.re"
	{ return (struct token){ TOK_INTEGER, index }; }
#line 132 "src/lexer.c"
yy23:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy25;
	default:	goto yy24;
	}
yy24:
	YYRESTORE ();
	goto yy3;
yy25:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy25;
	default:	goto yy27;
	}
yy27:
#line 42 "src/lexer.re"
	{ return (struct token){ 2, index }; }
#line 195 "src/lexer.c"
}
#line 51 "src/lexer.re"

}