/* Generated by re2c 3.0 */
#line 1 "src/lexer.re"
#include "basic/lexer.h"
#include "string.h"
#include "memory.h"
#include "debug.h"
#include <stdbool.h>

struct token lex(const char *input)
{
	int len = str_len(input);
	int marker;
	int ctxmarker;
	int index = 0;
	
	// Mark all variables as used
	(void)len;
	(void)marker;
	(void)ctxmarker;
	(void)index;
	
	if(*input == '\"')
	{
		int i;
		for(i = 1; input[i] != 0 && input[i] != '\"'; i++);
		if(input[i] == 0) {
			return (struct token){ TOKEN_INVALID, i };
		} else {
			return (struct token){ TOK_STRING, i + 1 };
		}
	}
	
#define YYCTYPE        char
#define YYPEEK()       input[index]
#define YYSKIP()       index++
#define YYBACKUP()     marker = index
#define YYBACKUPCTX()  ctxmarker = index
#define YYRESTORE()    index = marker
#define YYRESTORECTX() index = ctxmarker
#define YYLESSTHAN(n)  ((len - index) < (n))
#define YYFILL(n)      {}
	
#line 44 "src/lexer.c"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = YYPEEK();
	switch (yych) {
		case '\t': goto yy3;
		case 0x1A: goto yy6;
		case ' ': goto yy7;
		case '!': goto yy8;
		case '"': goto yy10;
		case '(': goto yy11;
		case ')': goto yy12;
		case '*': goto yy13;
		case '+': goto yy14;
		case ',': goto yy15;
		case '-': goto yy16;
		case '/': goto yy18;
		case '0': goto yy19;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy21;
		case ':': goto yy23;
		case '<': goto yy24;
		case '=': goto yy26;
		case '>': goto yy27;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'H':
		case 'J':
		case 'K':
		case 'M':
		case 'P':
		case 'Q':
		case 'R':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'p':
		case 'q':
		case 'r':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		case 'E':
		case 'e': goto yy32;
		case 'F':
		case 'f': goto yy33;
		case 'G':
		case 'g': goto yy34;
		case 'I':
		case 'i': goto yy35;
		case 'L':
		case 'l': goto yy36;
		case 'N':
		case 'n': goto yy37;
		case 'O':
		case 'o': goto yy38;
		case 'S':
		case 's': goto yy39;
		case 'T':
		case 't': goto yy40;
		default: goto yy1;
	}
yy1:
	YYSKIP();
yy2:
#line 55 "src/lexer.re"
	{ return (struct token){ TOKEN_INVALID, 0 }; }
#line 135 "src/lexer.c"
yy3:
	YYSKIP();
	yych = YYPEEK();
yy4:
	switch (yych) {
		case '\t':
		case ' ': goto yy3;
		default: goto yy5;
	}
yy5:
#line 68 "src/lexer.re"
	{ return (struct token){ TOKEN_WHITESPACE, index }; }
#line 148 "src/lexer.c"
yy6:
	YYSKIP();
#line 66 "src/lexer.re"
	{ return (struct token){ TOK_ASS, index }; }
#line 153 "src/lexer.c"
yy7:
	yyaccept = 0;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	switch (yych) {
		case 'A':
		case 'a': goto yy41;
		case 'O':
		case 'o': goto yy43;
		case 'X':
		case 'x': goto yy44;
		default: goto yy4;
	}
yy8:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '=': goto yy45;
		default: goto yy9;
	}
yy9:
#line 65 "src/lexer.re"
	{ return (struct token){ TOK_BANG, index }; }
#line 178 "src/lexer.c"
yy10:
	yyaccept = 1;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	if (yych <= 0x00) goto yy2;
	goto yy47;
yy11:
	YYSKIP();
#line 63 "src/lexer.re"
	{ return (struct token){ TOK_BRO, index }; }
#line 190 "src/lexer.c"
yy12:
	YYSKIP();
#line 64 "src/lexer.re"
	{ return (struct token){ TOK_BRC, index }; }
#line 195 "src/lexer.c"
yy13:
	YYSKIP();
#line 61 "src/lexer.re"
	{ return (struct token){ TOK_TIMES, index }; }
#line 200 "src/lexer.c"
yy14:
	YYSKIP();
#line 59 "src/lexer.re"
	{ return (struct token){ TOK_PLUS, index }; }
#line 205 "src/lexer.c"
yy15:
	YYSKIP();
#line 67 "src/lexer.re"
	{ return (struct token){ TOK_COMMA, index }; }
#line 210 "src/lexer.c"
yy16:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '>': goto yy6;
		default: goto yy17;
	}
yy17:
#line 60 "src/lexer.re"
	{ return (struct token){ TOK_MINUS, index }; }
#line 221 "src/lexer.c"
yy18:
	YYSKIP();
#line 62 "src/lexer.re"
	{ return (struct token){ TOK_DIVIDE, index }; }
#line 226 "src/lexer.c"
yy19:
	yyaccept = 2;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	switch (yych) {
		case 'X':
		case 'x': goto yy49;
		default: goto yy22;
	}
yy20:
#line 57 "src/lexer.re"
	{ return (struct token){ TOK_INTEGER, index }; }
#line 240 "src/lexer.c"
yy21:
	YYSKIP();
	yych = YYPEEK();
yy22:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy21;
		default: goto yy20;
	}
yy23:
	YYSKIP();
#line 58 "src/lexer.re"
	{ return (struct token){ TOKEN_EOL, index }; }
#line 262 "src/lexer.c"
yy24:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '=': goto yy50;
		default: goto yy25;
	}
yy25:
#line 85 "src/lexer.re"
	{ return (struct token){ TOK_LESS, index }; }
#line 273 "src/lexer.c"
yy26:
	YYSKIP();
#line 89 "src/lexer.re"
	{ return (struct token){ TOK_EQ, index }; }
#line 278 "src/lexer.c"
yy27:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '=': goto yy51;
		default: goto yy28;
	}
yy28:
#line 87 "src/lexer.re"
	{ return (struct token){ TOK_GREATER, index }; }
#line 289 "src/lexer.c"
yy29:
	YYSKIP();
	yych = YYPEEK();
yy30:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy31;
	}
yy31:
#line 83 "src/lexer.re"
	{ return (struct token){ TOK_ID, index }; }
#line 362 "src/lexer.c"
yy32:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'X':
		case 'x': goto yy52;
		default: goto yy30;
	}
yy33:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'A':
		case 'a': goto yy53;
		default: goto yy30;
	}
yy34:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'O':
		case 'o': goto yy54;
		default: goto yy30;
	}
yy35:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'F':
		case 'f': goto yy55;
		default: goto yy30;
	}
yy36:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'A':
		case 'a': goto yy57;
		default: goto yy30;
	}
yy37:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'O':
		case 'o': goto yy58;
		default: goto yy30;
	}
yy38:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'F':
		case 'f': goto yy59;
		case 'N':
		case 'n': goto yy60;
		default: goto yy30;
	}
yy39:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'T':
		case 't': goto yy62;
		default: goto yy30;
	}
yy40:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'R':
		case 'r': goto yy63;
		default: goto yy30;
	}
yy41:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'N':
		case 'n': goto yy64;
		default: goto yy42;
	}
yy42:
	YYRESTORE();
	switch (yyaccept) {
		case 0: goto yy5;
		case 1: goto yy2;
		case 2: goto yy20;
		default: goto yy31;
	}
yy43:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'R':
		case 'r': goto yy65;
		default: goto yy42;
	}
yy44:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'O':
		case 'o': goto yy66;
		default: goto yy42;
	}
yy45:
	YYSKIP();
#line 90 "src/lexer.re"
	{ return (struct token){ TOK_NEQ, index }; }
#line 473 "src/lexer.c"
yy46:
	YYSKIP();
	yych = YYPEEK();
yy47:
	switch (yych) {
		case 0x00: goto yy42;
		case '"': goto yy48;
		default: goto yy46;
	}
yy48:
	YYSKIP();
#line 69 "src/lexer.re"
	{ return (struct token){ TOK_STRING, index }; }
#line 487 "src/lexer.c"
yy49:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0': goto yy67;
		default: goto yy42;
	}
yy50:
	YYSKIP();
#line 86 "src/lexer.re"
	{ return (struct token){ TOK_LESSEQ, index }; }
#line 499 "src/lexer.c"
yy51:
	YYSKIP();
#line 88 "src/lexer.re"
	{ return (struct token){ TOK_GREATEREQ, index }; }
#line 504 "src/lexer.c"
yy52:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'I':
		case 'i': goto yy68;
		default: goto yy30;
	}
yy53:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'L':
		case 'l': goto yy69;
		default: goto yy30;
	}
yy54:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'T':
		case 't': goto yy70;
		default: goto yy30;
	}
yy55:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy56;
	}
yy56:
#line 79 "src/lexer.re"
	{ return (struct token){ TOKEN_IF, index }; }
#line 600 "src/lexer.c"
yy57:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'B':
		case 'b': goto yy71;
		default: goto yy30;
	}
yy58:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'T':
		case 't': goto yy72;
		default: goto yy30;
	}
yy59:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'F':
		case 'f': goto yy60;
		default: goto yy30;
	}
yy60:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy61;
	}
yy61:
#line 70 "src/lexer.re"
	{ return (struct token){ TOK_BOOL, index }; }
#line 696 "src/lexer.c"
yy62:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'O':
		case 'o': goto yy73;
		default: goto yy30;
	}
yy63:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'U':
		case 'u': goto yy74;
		default: goto yy30;
	}
yy64:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'D':
		case 'd': goto yy75;
		default: goto yy42;
	}
yy65:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case ' ': goto yy76;
		default: goto yy42;
	}
yy66:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'R':
		case 'r': goto yy77;
		default: goto yy42;
	}
yy67:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0': goto yy78;
		default: goto yy42;
	}
yy68:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'T':
		case 't': goto yy79;
		default: goto yy30;
	}
yy69:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'S':
		case 's': goto yy74;
		default: goto yy30;
	}
yy70:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'O':
		case 'o': goto yy81;
		default: goto yy30;
	}
yy71:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'E':
		case 'e': goto yy82;
		default: goto yy30;
	}
yy72:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case ' ': goto yy83;
		default: goto yy30;
	}
yy73:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'P':
		case 'p': goto yy84;
		default: goto yy30;
	}
yy74:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'E':
		case 'e': goto yy60;
		default: goto yy30;
	}
yy75:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case ' ': goto yy86;
		default: goto yy42;
	}
yy76:
	YYSKIP();
#line 74 "src/lexer.re"
	{ return (struct token){ TOK_OR, index }; }
#line 809 "src/lexer.c"
yy77:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case ' ': goto yy87;
		default: goto yy42;
	}
yy78:
	YYSKIP();
#line 56 "src/lexer.re"
	{ return (struct token){ TOKEN_EMPTY, 0 }; }
#line 821 "src/lexer.c"
yy79:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy80;
	}
yy80:
#line 81 "src/lexer.re"
	{ return (struct token){ TOKEN_EXIT, index }; }
#line 893 "src/lexer.c"
yy81:
	yyaccept = 3;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	switch (yych) {
		case '\t':
		case ' ': goto yy88;
		default: goto yy30;
	}
yy82:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case 'L':
		case 'l': goto yy89;
		default: goto yy30;
	}
yy83:
	YYSKIP();
#line 75 "src/lexer.re"
	{ return (struct token){ TOK_NOT, index }; }
#line 916 "src/lexer.c"
yy84:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy29;
		default: goto yy85;
	}
yy85:
#line 80 "src/lexer.re"
	{ return (struct token){ TOKEN_STOP, index }; }
#line 988 "src/lexer.c"
yy86:
	YYSKIP();
#line 72 "src/lexer.re"
	{ return (struct token){ TOK_AND, index }; }
#line 993 "src/lexer.c"
yy87:
	YYSKIP();
#line 73 "src/lexer.re"
	{ return (struct token){ TOK_XOR, index }; }
#line 998 "src/lexer.c"
yy88:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '\t':
		case ' ': goto yy88;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy90;
		default: goto yy42;
	}
yy89:
	yyaccept = 3;
	YYSKIP();
	YYBACKUP();
	yych = YYPEEK();
	switch (yych) {
		case '\t':
		case ' ': goto yy92;
		default: goto yy30;
	}
yy90:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy90;
		default: goto yy91;
	}
yy91:
#line 78 "src/lexer.re"
	{ return (struct token){ TOKEN_GOTO, index }; }
#line 1152 "src/lexer.c"
yy92:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '\t':
		case ' ': goto yy92;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy93;
		default: goto yy42;
	}
yy93:
	YYSKIP();
	yych = YYPEEK();
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy93;
		default: goto yy94;
	}
yy94:
#line 77 "src/lexer.re"
	{ return (struct token){ TOKEN_LABEL, index }; }
#line 1296 "src/lexer.c"
}
#line 91 "src/lexer.re"

}