/* Generated by re2c 0.16 */
#line 1 "src/lexer.re"
#include "basic/lexer.h"
#include "string.h"
#include "memory.h"
#include "debug.h"
#include <stdbool.h>

struct token lex(const char *input)
{
	int len = str_len(input);
	int marker;
	int ctxmarker;
	int index = 0;
	
	// Mark all variables as used
	(void)len;
	(void)marker;
	(void)ctxmarker;
	(void)index;
	
	if(*input == '\"')
	{
		int i;
		for(i = 1; input[i] != 0 && input[i] != '\"'; i++);
		if(input[i] == 0) {
			return (struct token){ TOKEN_INVALID, i };
		} else {
			return (struct token){ TOK_STRING, i + 1 };
		}
	}
	
#define YYCTYPE        char
#define YYPEEK()       input[index]
#define YYSKIP()       index++
#define YYBACKUP()     marker = index
#define YYBACKUPCTX()  ctxmarker = index
#define YYRESTORE()    index = marker
#define YYRESTORECTX() index = ctxmarker
#define YYLESSTHAN(n)  ((len - index) < (n))
#define YYFILL(n)      {}
	
#line 44 "src/lexer.c"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = YYPEEK ();
	switch (yych) {
	case '\t':	goto yy4;
	case 0x1A:	goto yy7;
	case ' ':	goto yy9;
	case '!':	goto yy10;
	case '"':	goto yy11;
	case '(':	goto yy12;
	case ')':	goto yy14;
	case '*':	goto yy16;
	case '+':	goto yy18;
	case ',':	goto yy20;
	case '-':	goto yy22;
	case '/':	goto yy24;
	case '0':	goto yy26;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy28;
	case ':':	goto yy30;
	case '<':	goto yy32;
	case '=':	goto yy34;
	case '>':	goto yy36;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'H':
	case 'J':
	case 'K':
	case 'M':
	case 'P':
	case 'Q':
	case 'R':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'p':
	case 'q':
	case 'r':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	case 'E':
	case 'e':	goto yy41;
	case 'F':
	case 'f':	goto yy42;
	case 'G':
	case 'g':	goto yy43;
	case 'I':
	case 'i':	goto yy44;
	case 'L':
	case 'l':	goto yy45;
	case 'N':
	case 'n':	goto yy46;
	case 'O':
	case 'o':	goto yy47;
	case 'S':
	case 's':	goto yy48;
	case 'T':
	case 't':	goto yy49;
	default:	goto yy2;
	}
yy2:
	YYSKIP ();
yy3:
#line 55 "src/lexer.re"
	{ return (struct token){ TOKEN_INVALID, 0 }; }
#line 135 "src/lexer.c"
yy4:
	YYSKIP ();
	yych = YYPEEK ();
yy5:
	switch (yych) {
	case '\t':
	case ' ':	goto yy4;
	default:	goto yy6;
	}
yy6:
#line 67 "src/lexer.re"
	{ return (struct token){ TOKEN_WHITESPACE, index }; }
#line 148 "src/lexer.c"
yy7:
	YYSKIP ();
#line 65 "src/lexer.re"
	{ return (struct token){ TOK_ASS, index }; }
#line 153 "src/lexer.c"
yy9:
	yyaccept = 0;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'A':
	case 'a':	goto yy50;
	case 'O':
	case 'o':	goto yy52;
	case 'X':
	case 'x':	goto yy53;
	default:	goto yy5;
	}
yy10:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '=':	goto yy54;
	default:	goto yy3;
	}
yy11:
	yyaccept = 1;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	if (yych <= 0x00) goto yy3;
	goto yy57;
yy12:
	YYSKIP ();
#line 63 "src/lexer.re"
	{ return (struct token){ TOK_BRO, index }; }
#line 186 "src/lexer.c"
yy14:
	YYSKIP ();
#line 64 "src/lexer.re"
	{ return (struct token){ TOK_BRC, index }; }
#line 191 "src/lexer.c"
yy16:
	YYSKIP ();
#line 61 "src/lexer.re"
	{ return (struct token){ TOK_TIMES, index }; }
#line 196 "src/lexer.c"
yy18:
	YYSKIP ();
#line 59 "src/lexer.re"
	{ return (struct token){ TOK_PLUS, index }; }
#line 201 "src/lexer.c"
yy20:
	YYSKIP ();
#line 66 "src/lexer.re"
	{ return (struct token){ TOK_COMMA, index }; }
#line 206 "src/lexer.c"
yy22:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '>':	goto yy7;
	default:	goto yy23;
	}
yy23:
#line 60 "src/lexer.re"
	{ return (struct token){ TOK_MINUS, index }; }
#line 216 "src/lexer.c"
yy24:
	YYSKIP ();
#line 62 "src/lexer.re"
	{ return (struct token){ TOK_DIVIDE, index }; }
#line 221 "src/lexer.c"
yy26:
	yyaccept = 2;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'X':
	case 'x':	goto yy60;
	default:	goto yy29;
	}
yy27:
#line 57 "src/lexer.re"
	{ return (struct token){ TOK_INTEGER, index }; }
#line 235 "src/lexer.c"
yy28:
	YYSKIP ();
	yych = YYPEEK ();
yy29:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy28;
	default:	goto yy27;
	}
yy30:
	YYSKIP ();
#line 58 "src/lexer.re"
	{ return (struct token){ TOKEN_EOL, index }; }
#line 257 "src/lexer.c"
yy32:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '=':	goto yy61;
	default:	goto yy33;
	}
yy33:
#line 84 "src/lexer.re"
	{ return (struct token){ TOK_LESS, index }; }
#line 267 "src/lexer.c"
yy34:
	YYSKIP ();
#line 88 "src/lexer.re"
	{ return (struct token){ TOK_EQ, index }; }
#line 272 "src/lexer.c"
yy36:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '=':	goto yy63;
	default:	goto yy37;
	}
yy37:
#line 86 "src/lexer.re"
	{ return (struct token){ TOK_GREATER, index }; }
#line 282 "src/lexer.c"
yy38:
	YYSKIP ();
	yych = YYPEEK ();
yy39:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	default:	goto yy40;
	}
yy40:
#line 82 "src/lexer.re"
	{ return (struct token){ TOK_ID, index }; }
#line 355 "src/lexer.c"
yy41:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'X':
	case 'x':	goto yy65;
	default:	goto yy39;
	}
yy42:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'A':
	case 'a':	goto yy66;
	default:	goto yy39;
	}
yy43:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'O':
	case 'o':	goto yy67;
	default:	goto yy39;
	}
yy44:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'F':
	case 'f':	goto yy68;
	default:	goto yy39;
	}
yy45:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'A':
	case 'a':	goto yy70;
	default:	goto yy39;
	}
yy46:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'O':
	case 'o':	goto yy71;
	default:	goto yy39;
	}
yy47:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'F':
	case 'f':	goto yy72;
	case 'N':
	case 'n':	goto yy73;
	default:	goto yy39;
	}
yy48:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'T':
	case 't':	goto yy75;
	default:	goto yy39;
	}
yy49:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'R':
	case 'r':	goto yy76;
	default:	goto yy39;
	}
yy50:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'N':
	case 'n':	goto yy77;
	default:	goto yy51;
	}
yy51:
	YYRESTORE ();
	switch (yyaccept) {
	case 0: 	goto yy6;
	case 1: 	goto yy3;
	case 2: 	goto yy27;
	default:	goto yy40;
	}
yy52:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'R':
	case 'r':	goto yy78;
	default:	goto yy51;
	}
yy53:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'O':
	case 'o':	goto yy79;
	default:	goto yy51;
	}
yy54:
	YYSKIP ();
#line 89 "src/lexer.re"
	{ return (struct token){ TOK_NEQ, index }; }
#line 466 "src/lexer.c"
yy56:
	YYSKIP ();
	yych = YYPEEK ();
yy57:
	switch (yych) {
	case 0x00:	goto yy51;
	case '"':	goto yy58;
	default:	goto yy56;
	}
yy58:
	YYSKIP ();
#line 68 "src/lexer.re"
	{ return (struct token){ TOK_STRING, index }; }
#line 480 "src/lexer.c"
yy60:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':	goto yy80;
	default:	goto yy51;
	}
yy61:
	YYSKIP ();
#line 85 "src/lexer.re"
	{ return (struct token){ TOK_LESSEQ, index }; }
#line 492 "src/lexer.c"
yy63:
	YYSKIP ();
#line 87 "src/lexer.re"
	{ return (struct token){ TOK_GREATEREQ, index }; }
#line 497 "src/lexer.c"
yy65:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'I':
	case 'i':	goto yy81;
	default:	goto yy39;
	}
yy66:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'L':
	case 'l':	goto yy82;
	default:	goto yy39;
	}
yy67:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'T':
	case 't':	goto yy83;
	default:	goto yy39;
	}
yy68:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	default:	goto yy69;
	}
yy69:
#line 78 "src/lexer.re"
	{ return (struct token){ TOKEN_IF, index }; }
#line 592 "src/lexer.c"
yy70:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'B':
	case 'b':	goto yy84;
	default:	goto yy39;
	}
yy71:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'T':
	case 't':	goto yy85;
	default:	goto yy39;
	}
yy72:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'F':
	case 'f':	goto yy73;
	default:	goto yy39;
	}
yy73:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	default:	goto yy74;
	}
yy74:
#line 69 "src/lexer.re"
	{ return (struct token){ TOK_BOOL, index }; }
#line 687 "src/lexer.c"
yy75:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'O':
	case 'o':	goto yy86;
	default:	goto yy39;
	}
yy76:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'U':
	case 'u':	goto yy87;
	default:	goto yy39;
	}
yy77:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'D':
	case 'd':	goto yy88;
	default:	goto yy51;
	}
yy78:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case ' ':	goto yy89;
	default:	goto yy51;
	}
yy79:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'R':
	case 'r':	goto yy91;
	default:	goto yy51;
	}
yy80:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':	goto yy92;
	default:	goto yy51;
	}
yy81:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'T':
	case 't':	goto yy94;
	default:	goto yy39;
	}
yy82:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'S':
	case 's':	goto yy87;
	default:	goto yy39;
	}
yy83:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'O':
	case 'o':	goto yy96;
	default:	goto yy39;
	}
yy84:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'E':
	case 'e':	goto yy97;
	default:	goto yy39;
	}
yy85:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case ' ':	goto yy98;
	default:	goto yy39;
	}
yy86:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'P':
	case 'p':	goto yy100;
	default:	goto yy39;
	}
yy87:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'E':
	case 'e':	goto yy73;
	default:	goto yy39;
	}
yy88:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case ' ':	goto yy102;
	default:	goto yy51;
	}
yy89:
	YYSKIP ();
#line 73 "src/lexer.re"
	{ return (struct token){ TOK_OR, index }; }
#line 800 "src/lexer.c"
yy91:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case ' ':	goto yy104;
	default:	goto yy51;
	}
yy92:
	YYSKIP ();
#line 56 "src/lexer.re"
	{ return (struct token){ TOKEN_EMPTY, 0 }; }
#line 812 "src/lexer.c"
yy94:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	default:	goto yy95;
	}
yy95:
#line 80 "src/lexer.re"
	{ return (struct token){ TOKEN_EXIT, index }; }
#line 883 "src/lexer.c"
yy96:
	yyaccept = 3;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy106;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	default:	goto yy40;
	}
yy97:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case 'L':
	case 'l':	goto yy108;
	default:	goto yy39;
	}
yy98:
	YYSKIP ();
#line 74 "src/lexer.re"
	{ return (struct token){ TOK_NOT, index }; }
#line 968 "src/lexer.c"
yy100:
	YYSKIP ();
	switch ((yych = YYPEEK ())) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	default:	goto yy101;
	}
yy101:
#line 79 "src/lexer.re"
	{ return (struct token){ TOKEN_STOP, index }; }
#line 1039 "src/lexer.c"
yy102:
	YYSKIP ();
#line 71 "src/lexer.re"
	{ return (struct token){ TOK_AND, index }; }
#line 1044 "src/lexer.c"
yy104:
	YYSKIP ();
#line 72 "src/lexer.re"
	{ return (struct token){ TOK_XOR, index }; }
#line 1049 "src/lexer.c"
yy106:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy106;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy109;
	default:	goto yy51;
	}
yy108:
	yyaccept = 3;
	YYSKIP ();
	YYBACKUP ();
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy112;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy38;
	default:	goto yy40;
	}
yy109:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy109;
	default:	goto yy111;
	}
yy111:
#line 77 "src/lexer.re"
	{ return (struct token){ TOKEN_GOTO, index }; }
#line 1265 "src/lexer.c"
yy112:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '\t':
	case ' ':	goto yy112;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy114;
	default:	goto yy51;
	}
yy114:
	YYSKIP ();
	yych = YYPEEK ();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy114;
	default:	goto yy116;
	}
yy116:
#line 76 "src/lexer.re"
	{ return (struct token){ TOKEN_LABEL, index }; }
#line 1409 "src/lexer.c"
}
#line 90 "src/lexer.re"

}